name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "[+] Stopping and removing old container if exists..."
          docker stop flask-todo-app || true
          docker rm flask-todo-app || true

          echo "[+] Freeing up port 80..."
          # Kill any container using port 80 (in case name was changed or container failed)
          docker ps --filter "publish=80" -q | xargs -r docker stop
          docker ps -a --filter "publish=80" -q | xargs -r docker rm

          echo "[+] Removing old image if needed..."
          docker image ls | grep flask-todo-app && docker rmi -f r0ny17/flask-todo-app:latest || true

          echo "[+] Pulling latest image..."
          docker pull r0ny17/flask-todo-app:latest

          echo "[+] Starting new container..."
          docker run -d -p 80:5000 --name flask-todo-app r0ny17/flask-todo-app:latest
        EOF